### ISSUE TITLE
There are some bugs in tridistribute.cpp, wrong variable names, and lack of "}" 

### ISSUE THREAD

**Issue by takeher** [RickyLLu/CO2Net#1]
After fixing these variable name inconsistencies in tridistribute.cpp,  setup.sh can run successfully, but encounter the following problems when running the evaluate script:

Traceback (most recent call last):
  File "scripts/evaluate_model.py", line 24, in <module>
    from iharm.model.base import SSAMvideoLutWithoutDbp, SSAMvideoLut
  File "./iharm/model/base/__init__.py", line 2, in <module>
    from .ssam_video_lut_dbp import SSAMvideoLut
  File "./iharm/model/base/ssam_video_lut_dbp.py", line 19, in <module>
    from iharm.model.modeling.lut import TrilinearInterpolation, TridistributeGeneraotr
  File "./iharm/model/modeling/lut.py", line 11, in <module>
    import tridistribute
ImportError: /home/ubuntu/anaconda3/envs/torch/lib/python3.7/site-packages/tridistribute-0.0.0-py3.7-linux-x86_64.egg/tridistribute.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z22tridistribute_backwardN2at6TensorES0_S0_S0_iifiii

There may be some other bugs in tridistribute module and cause my build failed. How can I solve it?

**Comment by RickyLLu** [comment]
Thanks for your email. Do you compile with CUDA? Actually I focus on CUDA version of tridistribute since it would be slow if there is no GPU and there may be some bugs in non-gpu version. 
    	
    
  

 发件人: car1999 ***@***.***>发送时间: 星期三, 六月 15, 2022 10:40 下午收件人: RickyLLu/CO2Net ***@***.***>抄送: Subscribed ***@***.***>主题: [RickyLLu/CO2Net] There are some bugs in tridistribute.cpp, wrong variable names, and lack of "}"  (Issue #1) 
After fixing these variable name inconsistencies in tridistribute.cpp,  setup.sh can run successfully, but encounter the following problems when running the evaluate script:
Traceback (most recent call last):
File "scripts/evaluate_model.py", line 24, in 
from iharm.model.base import SSAMvideoLutWithoutDbp, SSAMvideoLut
File "./iharm/model/base/init.py", line 2, in 
from .ssam_video_lut_dbp import SSAMvideoLut
File "./iharm/model/base/ssam_video_lut_dbp.py", line 19, in 
from iharm.model.modeling.lut import TrilinearInterpolation, TridistributeGeneraotr
File "./iharm/model/modeling/lut.py", line 11, in 
import tridistribute
ImportError: /home/ubuntu/anaconda3/envs/torch/lib/python3.7/site-packages/tridistribute-0.0.0-py3.7-linux-x86_64.egg/tridistribute.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z22tridistribute_backwardN2at6TensorES0_S0_S0_iifiii
There may be some other bugs in tridistribute module and cause my build failed. How can I solve it?

**Comment by takeher** [comment]
> Thanks for your email. Do you compile with CUDA? Actually I focus on CUDA version of tridistribute since it would be slow if there is no GPU and there may be some bugs in non-gpu version.   发件人: car1999 ***@***.***>发送时间: 星期三, 六月 15, 2022 10:40 下午收件人: RickyLLu/CO2Net ***@***.***>抄送: Subscribed ***@***.***>主题: [RickyLLu/CO2Net] There are some bugs in tridistribute.cpp, wrong variable names, and lack of "}" (Issue #1)  After fixing these variable name inconsistencies in tridistribute.cpp, setup.sh can run successfully, but encounter the following problems when running the evaluate script: Traceback (most recent call last): File "scripts/evaluate_model.py", line 24, in from iharm.model.base import SSAMvideoLutWithoutDbp, SSAMvideoLut File "./iharm/model/base/init.py", line 2, in from .ssam_video_lut_dbp import SSAMvideoLut File "./iharm/model/base/ssam_video_lut_dbp.py", line 19, in from iharm.model.modeling.lut import TrilinearInterpolation, TridistributeGeneraotr File "./iharm/model/modeling/lut.py", line 11, in import tridistribute ImportError: /home/ubuntu/anaconda3/envs/torch/lib/python3.7/site-packages/tridistribute-0.0.0-py3.7-linux-x86_64.egg/tridistribute.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z22tridistribute_backwardN2at6TensorES0_S0_S0_iifiii There may be some other bugs in tridistribute module and cause my build failed. How can I solve it? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you!  I find it works. The CUDA version can run successfully and get correct test results. My compilation environment is pytorch-1.8.1, CUDA-10.2, gcc-8.4.0, while compiled without errors. I wil close this issue but still hope to have a cpu version with no bugs. Thx!

**Comment by RickyLLu** [comment]
Thanks for your email. Do you compile with CUDA? Actually I focus on CUDA version of tridistribute since it would be slow if there is no GPU and there may be some bugs in non-gpu version. 
    	
    
  

 发件人: car1999 ***@***.***>发送时间: 星期三, 六月 15, 2022 10:40 下午收件人: RickyLLu/CO2Net ***@***.***>抄送: Subscribed ***@***.***>主题: [RickyLLu/CO2Net] There are some bugs in tridistribute.cpp, wrong variable names, and lack of "}"  (Issue #1) 
After fixing these variable name inconsistencies in tridistribute.cpp,  setup.sh can run successfully, but encounter the following problems when running the evaluate script:
Traceback (most recent call last):
File "scripts/evaluate_model.py", line 24, in 
from iharm.model.base import SSAMvideoLutWithoutDbp, SSAMvideoLut
File "./iharm/model/base/init.py", line 2, in 
from .ssam_video_lut_dbp import SSAMvideoLut
File "./iharm/model/base/ssam_video_lut_dbp.py", line 19, in 
from iharm.model.modeling.lut import TrilinearInterpolation, TridistributeGeneraotr
File "./iharm/model/modeling/lut.py", line 11, in 
import tridistribute
ImportError: /home/ubuntu/anaconda3/envs/torch/lib/python3.7/site-packages/tridistribute-0.0.0-py3.7-linux-x86_64.egg/tridistribute.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z22tridistribute_backwardN2at6TensorES0_S0_S0_iifiii
There may be some other bugs in tridistribute module and cause my build failed. How can I solve it?
